print("However! There is still the numerical precision issue.")
print("If x >= 0.5, log_zeta_continuation_with_derivatives calculates:")
print("z_data = zeta_with_derivatives(x, y)")
print("z_val = z_data[0]")
print("z_dx = z_data[1]")
print("val = log(z_val)")
print("dx = z_dx / z_val")
print("Then zeta_continuation_with_derivatives calculates:")
print("val_out = exp(val) = exp(log(z_val))")
print("dx_out = exp(val) * dx = exp(log(z_val)) * z_dx / z_val")
print("If z_val is exactly 0 or < 1e-24 (which is mag_sq < 1e-48), complex_log returns (-60, 0).")
print("exp(-60, 0) is roughly 8e-27.")
print("But z_dx is not 0. Let's say z_dx is 1.")
print("dx = 1 / z_val. But complex_div(1, 0) will use a denominator bounded by 1e-24.")
print("dx = 1 / 1e-24 = 1e24.")
print("So dx_out = 8e-27 * 1e24 = 0.008.")
print("Which is not z_dx (which was 1)!")
print("This floating point issue will ALWAYS happen if z_val is very close to 0.")
print("To fix this algebraically, zeta_continuation_with_derivatives should check if x >= 0.5 and just return zeta_with_derivatives(x, y, iters)!")
