print("z_val is near 0. denom is 1e-24 + ~0.")
print("dx = complex_div(z_dx, z_val) -> division by a very small number.")
print("So dx is huge in log_zeta_continuation_with_derivatives.")
print("Then in zeta_continuation_with_derivatives:")
print("val = complex_exp(log_z[0]) -> exp(-60) -> ~0.")
print("dx = complex_mul(val, log_z[1]) -> ~0 * HUGE.")
print("This creates floating point inaccuracy! ~1e-26 * 1e24 -> something completely random.")
print("So dx is wrong at exactly the zero.")
print("Because test_zeta_continuation_with_derivatives evaluated exactly at the zero, the test fails.")
