print("Wait, what does complex_log do if the magnitude is small?")
print("mag_sq < 1e-48")
print("return Vector2(-60.0, 0.0)")
print("complex_exp(-60.0, 0.0) -> exp(-60) is ~1e-26")
print("So val = exp(log(z)) is ~1e-26.")
print("But test says res[0].x is -0.0335!")
print("Why would val be -0.0335??")
print("Ah!!")
print("Because x = 0.5.")
print("In zeta_continuation_with_derivatives(x, y, iters):")
print("var log_z = log_zeta_continuation_with_derivatives(x, y, iters)")
print("iters is passed as 10 from the test!")
print("But in zeta_continuation:")
print("var log_val = log_zeta_continuation(x, y)")
print("And log_zeta_continuation does:")
print("var z = zeta(x, y)")
print("And zeta does:")
print("var iterations = Config.iterations")
print("So zeta_continuation uses Config.iterations (default 2000 in tests, wait, no, default is 100 or something)")
print("But test_zeta_continuation_with_derivatives explicitly passes `iters=10`!")
print("zeta(0.5, 14.134725) with 10 iterations is NOT zero!")
print("It's some random value!")
