print("Because test_zeta_continuation does:")
print("res = zeta_continuation(0.5, ...)")
print("assert_almost_eq(res.x, 0.0, 0.015)")
print("zeta(0.5, 14.134725) is near zero, say (1e-6, 1e-6).")
print("log(1e-6, 1e-6) -> log_mag = -14, angle = pi/4.")
print("exp(-14, pi/4) -> near zero.")
print("So it goes near zero -> log -> large negative -> exp -> near zero.")
print("But for the derivative:")
print("dx = complex_div(z_dx, z_val)")
print("z_val = 1e-6, z_dx = ~1.0 (some non-zero).")
print("complex_div(1.0, 1e-6) -> 1e6")
print("dx = 1e6.")
print("Then dx_out = exp(-14) * 1e6 = 1e-6 * 1e6 = 1.0.")
print("Mathematically this should cancel out exactly: exp(log(z)) * z'/z = z * z'/z = z'.")
print("But wait... test output showed:")
print("val_pure.x is 0.000036")
print("res[0].x is -0.0335")
print("Why is val different between zeta_continuation and zeta_continuation_with_derivatives for x=0.5?")
